// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LIFT_H
#define LIFT_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Lift: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* speedController;
	Encoder* encoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Lift();
	void InitDefaultCommand();
	void LiftUpFast();
	void LiftDownFast();
	void LiftUpSlow();
	void LiftDownSlow();

	void PutDashboardValues();
	void ReadDashboardValues();

	//constants for smart dashboard displaying
	const std::string LIFT_SPEED_UP_FAST_KEY = "Lift::Lift Speed Up Fast";
	const float LIFT_SPEED_UP_FAST_DEFAULT = 1;

	const std::string LIFT_SPEED_DOWN_FAST_KEY = "Lift::Lift Speed Down Fast";
	const float LIFT_SPEED_DOWN_FAST_DEFAULT = -1;

	const std::string LIFT_SPEED_UP_SLOW_KEY = "Lift::Lift Speed Up Slow";
	const float LIFT_SPEED_UP_SLOW_DEFAULT = .2;

	const std::string LIFT_SPEED_DOWN_SLOW_KEY = "Lift::Lift Speed Down Slow";
	const float LIFT_SPEED_DOWN_SLOW_DEFAULT = -.2;

	//variables for reading smart dashboard values
	float liftSpeedUpFast;
	float liftSpeedDownFast;
	float liftSpeedUpSlow;
	float liftSpeedDownSlow;



};

#endif
