// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LIFT_H
#define LIFT_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Lift: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* speedController;
	Encoder* encoder;
	DoubleSolenoid * brakesolenoid;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	Lift();
	void InitDefaultCommand();
	void LiftUpFast();
	void LiftDownFast();
	void LiftUpSlow();
	void LiftDownSlow();
	void BrakeOn();
	void BrakeOff();
	void BrakePowerOff();
	void UpdateSmartDashboard();


	void PutDashboardValues();
	void ReadDashboardValues();
	int CurrentLiftPosition();

	//constants for smart dashboard displaying
	const std::string LIFT_SPEED_UP_FAST_KEY = "Lift::Lift Speed Up Fast";
	const float LIFT_SPEED_UP_FAST_DEFAULT = 1;

	const std::string LIFT_SPEED_DOWN_FAST_KEY = "Lift::Lift Speed Down Fast";
	const float LIFT_SPEED_DOWN_FAST_DEFAULT = -1;

	const std::string LIFT_SPEED_UP_SLOW_KEY = "Lift::Lift Speed Up Slow";
	const float LIFT_SPEED_UP_SLOW_DEFAULT = .2;

	const std::string LIFT_SPEED_DOWN_SLOW_KEY = "Lift::Lift Speed Down Slow";
	const float LIFT_SPEED_DOWN_SLOW_DEFAULT = -.2;

	const std::string LIFT_ENCODER_VALUE_DASHBOARD_KEY = "Lift::Encoder Tick Value:";
	const float LIFT_ENCODER_VALUE_DEFAULT = -5;

	//variables for reading smart dashboard values
	float liftSpeedUpFast;
	float liftSpeedDownFast;
	float liftSpeedUpSlow;
	float liftSpeedDownSlow;

	const int LIFT_DEADBAND_DEFAULT = 1024; // 1/8 of the total ticks in one rotation of the encoder
	const int TICKS_LIFT_DEFAULT = 30000;
	const int SPEED_LIFT_DEFAULT = .2;

	const int ENCODER_LIFT_TICKS = 8192;// full encoder rotation
	const float TOTLA_LIFT_TURNS = 8.4;// how many rotations the ecoder must make to reach the desired height
	const int MAX_LIFT_TICKS = ENCODER_LIFT_TICKS * ENCODER_LIFT_TICKS;

	const int UPPER_DEADBAND = 1000;
	const int LOWER_DEADBAND = 100;
	const int UPPER_SAFETY_LIMIT = MAX_LIFT_TICKS - UPPER_DEADBAND;
	const int LOWER_SAFETY_LIMIT = LOWER_DEADBAND + 0;


};

#endif
