// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef AUTON3TOTESTACK_H
#define AUTON3TOTESTACK_H

#include "Commands/CommandGroup.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Auton3ToteStack: public CommandGroup {
public:
	Auton3ToteStack();
	const float SPEED_UP = .7;
	const float SPEED_DOWN = .4;
	const float TOTE_ONE_ENGAGE_TICKS = 0;
	//TODO: MATH FOR CONSTANT TICK VALUE BELOW
	const float TOTE_TWO_ENGAGE_TICKS = 0;
	const float TOTE_THREE_ENGAGE_TICKS = 0;
	const float GO_OVER_BIN_TICKS = 0;
};

#endif
