// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVE2FEET_H
#define DRIVE2FEET_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Drive2Feet: public Command {
public:
	Drive2Feet();
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
	float TICKS_NEEDED;
	float p;
	const std::string PROPORTIONAL_CONSTANT_DASHBOARD_KEY = "Drive2Feet::Proportional Constant";
	const std::string TICKS_NEEDED_DASHBOARD_KEY = "Drive2Feet::Ticks Needed";
	const std::string MAX_PERCENT_DASHBOARD_KEY = "Drive2Feet::Max Percent";
	const std::string INTEGRAL_CONSTANT_DAHSBOARD_KEY = "Drive2Feet::Integral Constant";
	const std::string CLOSED_LOOP_RAMP_RATE_DASHBOARD_KEY = "Drive2Feet::Closed Loop Ramp Rate";
	const std::string CLOSED_LOOP_ERROR_DASHBOARD_KEY = "Drive2Feet::Closed Loop Error";
	const std::string ENCODER_POSITION_DASHBOARD_KEY = "Drive2Feet::Encoder Position";

	PIDController*frontLeftPIDController;
	PIDController*frontRightPIDController;
	PIDController*rearLeftPIDController;
	PIDController*rearRightPIDController;

	const double PROPORTIONAL_CONSTANT_DEFAULT = 1;
	const double MAX_PERCENT_DEFAULT = 6;
	const double INTEGRAL_CONSTANT_DEFAULT = 0;
	const double CLOSED_LOOP_RAMP_RATE_DEFAULT = 0;
	const double CLOSED_LOOP_ERROR_DEFAULT = 0;
	const double ENCODER_POSITION_DEFAULT = 0;



};

#endif
