// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef DRIVEXFEET_H
#define DRIVEXFEET_H

#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveXFeet: public Command {
public:
	DriveXFeet(float = -1, float = 0);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
	float maxpercent;
	float feet;
	const float FEET_DEFAULT = 2;
	const std::string DISTANCE_TO_TRAVEL_IN_FEET_DASHBOARD_KEY =
			"DriveXFeet::Distance to Travel in Feet";
	const float MAXPERCENT_DEFAULT = 0;
	const std::string MAX_PERCENT_DASHBOARD_KEY = "DriveXFeet::Max Percent:";
};

#endif
