// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "DriveXFeet.h"
#include "../RobotMap.h"

DriveXFeet::DriveXFeet(float f, float m) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	feet = f;
	maxpercent = m;

}

// Called just before this Command runs the first time
void DriveXFeet::Initialize() {
	this->SetTimeout( (1.0069 * feet)  - (6 * maxpercent) + 1.7448);

	Robot::driveTrain->ResetDistance();
	Robot::driveTrain->SetDistanceInFeet(feet);
	Robot::driveTrain->SetPIDControllerOutputRange(maxpercent);

}

// Called repeatedly when this Command is scheduled to run
void DriveXFeet::Execute() {
	Robot::driveTrain->UpdateDashboard();
}

// Make this return true when this Command no longer needs to run execute()
bool DriveXFeet::IsFinished() {

	return Robot::driveTrain->AtDestination() || this->IsTimedOut();
}

// Called once after isFinished returns true
void DriveXFeet::End() {
	Robot::driveTrain->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveXFeet::Interrupted() {
	End();
}
