// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LIFTSDBTICKS_H
#define LIFTSDBTICKS_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class LiftSDBTicks: public Command {
public:
	LiftSDBTicks();
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

	const std::string LIFT_TICKS_DASHBOARD_KEY = "LiftSDBTicks: Ticks to Lift: ";
	const std::string LIFT_SPEED_DASHBOARD_KEY =  "Lift SDBTicks: Speed: ";
	const float TICKS_LIFT_DEFAULT = 0;
	const float SPEED_LIFT_DEFAULT = .4;
	float speed;
	float ticks;
};

#endif
