// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "LiftXTicks.h"

LiftXTicks::LiftXTicks(int t, float s) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::lift);

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	// intiliatizes speed and tick values sent in
	speed = s;		// postive indicates lift up, negative indicates lift down
	ticks = t;		// where the lift is to end
}

// Called just before this Command runs the first time
void LiftXTicks::Initialize() {

	this->SetTimeout(10); // sets timeout for safety

}

// Called repeatedly when this Command is scheduled to run
void LiftXTicks::Execute() {

	Robot::lift->UpdateSmartDashboard();
	Robot::lift->SetLift(ticks, speed);

}

// Make this return true when this Command no longer needs to run execute()
bool LiftXTicks::IsFinished() {

	return Robot::lift->AtDestination() || this->IsTimedOut();

}

// Called once after isFinished returns true
void LiftXTicks::End() {
	Robot::lift->Stop();

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void LiftXTicks::Interrupted() {

	End();

}
