// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef LIFTUPFAST_H
#define LIFTUPFAST_H

#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class LiftUpFast: public Command {
public:

	const std::string LIFT_ENCODER_MAX_STRING = "Lift Encoder Allowed Max: ";
	const int encoder_lift_ticks = 8192;
	const float total_lift_turns = 8.4;
	const int LIFT_ENCODER_MAX = encoder_lift_ticks * total_lift_turns;
	int maxHeight = 0;

	const std::string DEADBAND_STRING = "Deadband: ";
	const int DEADBAND_VALUE = 1024;

	float encoderLiftvalue = 0;

	double deadband = 0;

	LiftUpFast();
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
};

#endif
