// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LIFTUPSLOW_H
#define LIFTUPSLOW_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class LiftUpSlow: public Command {
public:

	const std::string LIFT_ENCODER_MAX_STRING = "Lift Encoder Allowed Max: ";
	const int LIFT_ENCODER_MAX = 2000;
	int maxHeight = 0;

	const std::string OFFSET_LIFT_MAX = "Lift offset max: ";
	const int OFFSET_LIFT_DEFAULT_MAX = 50;

	const std::string OFFSET_LIFT_MIN = "Lift offset min: ";
	const int OFFSET_LIFT_DEFAULT_MIN = 50;

	float encoderLiftvalue = 0;

	int offsetmin = 0;
	int offsetmax = 0;


	LiftUpSlow();
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
};

#endif
