// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LIFTDOWNSLOW_H
#define LIFTDOWNSLOW_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class LiftDownSlow: public Command {
public:

	const std::string LIFT_ENCODER_MIN_STRING = "Lift Encoder Allowed Min: ";
	const int LIFT_ENCODER_MIN = 0;
	int minHeight = 0;

	const std::string DEADBAND_STRING = "Deadband: ";
	const int DEADBAND_VALUE = 1024;

	float encoderLiftvalue = 0;

	double deadband = 0;


	LiftDownSlow();
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
};

#endif
