// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "Trashbin_Auto.h"

#include "DriveXFeet.h"
#include "StrafeXFeet.h"
#include "WinchIn.h"
#include "WinchOut.h"

Trashbin_Auto::Trashbin_Auto() {

	AddSequential(new DriveXFeet(-2.15833));
	AddSequential(new WinchOut());

	AddSequential(new StrafeXFeet(1));
	AddSequential(new WinchIn());

	AddSequential(new StrafeXFeet(-1));
	AddSequential(new DriveXFeet(-5.725));
	AddSequential(new WinchOut());

	AddSequential(new StrafeXFeet(1));
	AddSequential(new WinchIn());
	AddSequential(new StrafeXFeet(-1));


	AddSequential(new DriveXFeet(-8.1083));
	AddSequential(new WinchOut());

	AddSequential(new StrafeXFeet(1));
	AddSequential(new WinchIn());

	AddSequential(new StrafeXFeet(-1));
	AddSequential(new DriveXFeet(-5.725));
	AddSequential(new WinchOut());

	AddSequential(new StrafeXFeet(1));
	AddSequential(new WinchIn());

	AddSequential(new StrafeXFeet(-1));

}
