// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "TurnNDegrees.h"
#include "math.h"

TurnNDegrees::TurnNDegrees(float d) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	// the following SmartDashboard values are for setting up defaults
	SmartDashboard::PutNumber(ANGLE_TO_TURN, TURNING_DEFAULT);
	SmartDashboard::PutNumber(TURNING_SPEED, TURNING_SPEED_DEFAULT);
	SmartDashboard::PutNumber(DEADTURN_STRING, DEADTURN_DEFAULT);

}

// Called just before this Command runs the first time
void TurnNDegrees::Initialize() {

	this->SetTimeout(10); // 10 sec safety timer

	degreesturning = d;

	//if (degreesturning == 0) // if the command accually sends a value and is needed to be changed
	//{
	degreesturning = SmartDashboard::GetNumber(ANGLE_TO_TURN, TURNING_DEFAULT);
	speed = SmartDashboard::GetNumber(TURNING_SPEED, TURNING_SPEED_DEFAULT);
	deadturn = SmartDashboard::GetNumber(DEADTURN_STRING, DEADTURN_DEFAULT); // gives deadturn a value from the smartdashboard

	//speed = abs(speed); // makes sure that speed is a positive value

	// degreesturing can take a negative or a positive value, speed cannot for desired results
	//}
	startAngle = Robot::driveTrain->driveGyro->GetAngle(); // gets the starting angle for the command

	finalAngle = degreesturning + startAngle; // gives finalangle a value
	SmartDashboard::PutNumber("Final angle: ", finalAngle); // tells us the ending program

}

// Called repeatedly when this Command is scheduled to run
void TurnNDegrees::Execute() {

	if (degreesturning > 0)
		Robot::driveTrain->drive(0, 0, speed); // clockwise

	if (degreesturning < 0)
		Robot::driveTrain->drive(0, 0, speed * -1); //  counter-clockwise

	angleAt = Robot::driveTrain->driveGyro->GetAngle(); // angle the robot is currently at

	SmartDashboard::PutNumber("Current angle: ", angleAt); // current angle we are at
	SmartDashboard::PutNumber("Active speed: ", speed);
}

// Make this return true when this Command no longer needs to run execute()
bool TurnNDegrees::IsFinished() {

	if (((angleAt <= finalAngle + deadturn && angleAt >= finalAngle - deadturn)
			|| this->IsTimedOut()))
		// when timer is done it will end the command
		// checks to see if the angle turned is withing the desired angle range
		return true;

	else
		return false;
}

// Called once after isFinished returns true
void TurnNDegrees::End() {
	Robot::driveTrain->drive(0, 0, 0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TurnNDegrees::Interrupted() {
	End();
}

