// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "WinchIn.h"
#include "../Subsystems/WinchSystem.h"

WinchIn::WinchIn(float sp) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::winchSystem);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	SP = sp;
}

// Called just before this Command runs the first time
void WinchIn::Initialize() {
	//Time needed to drive at 100% voltage/speed
	const float timeConstL2H = 1.5;
	const float timeConstM2H = 1.0;
	const float timeConstL2M = 0.5;
	//Motor speed constant (including +/-)
	const float motorSpeed = 1.0;
	//Time needed to drive (actual time with speed correction)
	const float moveTimeL2H = timeConstL2H/motorSpeed;
	const float moveTimeM2H = timeConstM2H/motorSpeed;
	const float moveTimeL2M = timeConstL2M/motorSpeed;

	if (Robot::winchSystem->Winch_Position == 0 && SP == 0)
		SetTimeout(moveTimeM2H);
	if (Robot::winchSystem->Winch_Position == 2 && SP == 0)
		SetTimeout(moveTimeL2H);
	if (Robot::winchSystem->Winch_Position == 2 && SP == 1)
		SetTimeout(moveTimeL2M);
}

// Called repeatedly when this Command is scheduled to run
void WinchIn::Execute() {
	
	if (this -> IsTimedOut() != true )
		Robot::winchSystem->winchMotor->Set(.5);
}

// Make this return true when this Command no longer needs to run execute()
bool WinchIn::IsFinished() {
	if (this -> IsTimedOut() == true)
		return true;

	return false;
}

// Called once after isFinished returns true
void WinchIn::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void WinchIn::Interrupted() {

}
