// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "WinchPositionSelector.h"
#include "../Commands/WinchIn.h"
#include "../Commands/WinchOut.h"

WinchPositionSelector::WinchPositionSelector() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void WinchPositionSelector::Initialize() {

	if (winchPosH && !winchPosM && !winchPosL) // true, false, false
		WinchIn(0);

	else if (!winchPosH && winchPosM && !winchPosL) { // false, true, false

		if (winchCurrentPos == 0)
			WinchOut(1);
		else if (winchCurrentPos == 2)
			WinchIn(1);

	}

	else if (!winchPosH && !winchPosM && winchPosL) // false, false, true
		WinchOut(2);

}

// Called repeatedly when this Command is scheduled to run
void WinchPositionSelector::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool WinchPositionSelector::IsFinished() {
	return true;
}

// Called once after isFinished returns true
void WinchPositionSelector::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void WinchPositionSelector::Interrupted() {

}
